/**
 * Memory Bank Types
 * Defines the data structures for the memory bank feature
 */

/**
 * Memory Item - Represents a single memory entry
 */
export interface MemoryItem {
  id: string;
  content: string;
  source: MemorySource;
  category: MemoryCategory;
  tags: string[];
  createdAt: string;
  updatedAt: string;
  relevanceScore?: number;
  metadata?: Record<string, any>;
}

/**
 * Memory Source - Where the memory originated from
 */
export type MemorySource = 
  | 'chat'        // From a chat conversation
  | 'user'        // Manually added by user
  | 'document'    // From an uploaded document
  | 'web'         // From web search
  | 'system';     // Generated by the system

/**
 * Memory Category - Classification of memory type
 */
export type MemoryCategory = 
  | 'fact'        // Factual information
  | 'insight'     // Analysis or insight
  | 'question'    // Important question
  | 'action'      // Action item or task
  | 'reference'   // Reference to external content
  | 'custom';     // User-defined category

/**
 * Memory Filter - Used to filter memory items
 */
export interface MemoryFilter {
  searchTerm?: string;
  categories?: MemoryCategory[];
  sources?: MemorySource[];
  tags?: string[];
  dateRange?: {
    start?: string;
    end?: string;
  };
  sortBy?: 'createdAt' | 'updatedAt' | 'relevance';
  sortDirection?: 'asc' | 'desc';
}

/**
 * Memory Context - Contextual information about a memory
 */
export interface MemoryContext {
  chatId?: string;
  messageId?: string;
  documentId?: string;
  url?: string;
  relatedMemories?: string[]; // IDs of related memories
}

/**
 * Memory Bank Stats - Statistical information about the memory bank
 */
export interface MemoryBankStats {
  totalMemories: number;
  categoryCounts: Record<MemoryCategory, number>;
  sourceCounts: Record<MemorySource, number>;
  topTags: Array<{tag: string, count: number}>;
  lastUpdated: string;
}